name: starcy
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: 10.0.1
  cupertino_icons: 1.0.2
  cupertino_modal_sheet: 1.1.0
  device_preview: 1.2.0
  equatable: 2.0.5
  flutter_bloc: 8.1.3
  flutter_dotenv: ^5.2.1
  flutter_screenutil: 5.9.0
  font_awesome_flutter: 10.6.0
  google_sign_in: 6.3.0
  just_audio: ^0.10.2
  logger: 2.0.2+1
  record: ^6.0.0
  shared_preferences: ^2.2.2
  supabase_flutter: 2.8.4
  url_launcher: 6.3.1
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  build_runner: 2.4.15
  auto_route_generator: 10.0.1
  flutter_launcher_icons: "^0.14.3"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/google_logo.png
    - assets/images/apple_logo.png
    - assets/images/starcy_logo.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
