// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOS8voGKY_3YO3oMHK2S0oQOpLT3qJex0',
    appId: '1:760107320718:web:3d309a69ac12e46e9150df',
    messagingSenderId: '760107320718',
    projectId: 'starcy-171f1',
    authDomain: 'starcy-171f1.firebaseapp.com',
    storageBucket: 'starcy-171f1.firebasestorage.app',
    measurementId: 'G-0H81MHJT8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJEU-68B3mbIUO9Rt3ih8YeLu7AsCVQWk',
    appId: '1:760107320718:android:5c3c54a180585acd9150df',
    messagingSenderId: '760107320718',
    projectId: 'starcy-171f1',
    storageBucket: 'starcy-171f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB749T7rfGxwSV-K2TjbEt_JhAC0dI90V4',
    appId: '1:760107320718:ios:8246bf88743fcbf49150df',
    messagingSenderId: '760107320718',
    projectId: 'starcy-171f1',
    storageBucket: 'starcy-171f1.firebasestorage.app',
    iosBundleId: 'com.starcy.app.starcy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB749T7rfGxwSV-K2TjbEt_JhAC0dI90V4',
    appId: '1:760107320718:ios:8246bf88743fcbf49150df',
    messagingSenderId: '760107320718',
    projectId: 'starcy-171f1',
    storageBucket: 'starcy-171f1.firebasestorage.app',
    iosBundleId: 'com.starcy.app.starcy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOS8voGKY_3YO3oMHK2S0oQOpLT3qJex0',
    appId: '1:760107320718:web:1fba7cfd7dd6ebbb9150df',
    messagingSenderId: '760107320718',
    projectId: 'starcy-171f1',
    authDomain: 'starcy-171f1.firebaseapp.com',
    storageBucket: 'starcy-171f1.firebasestorage.app',
    measurementId: 'G-27624VBEVJ',
  );
}
